export const INDIAN_TRAVEL_LOCATIONS = [
  "Goa",
  "Mumbai",
  "Jaipur",
  "New Delhi",
  "Agra",
  "Udaipur",
  "Varanasi",
  "Rishikesh",
  "Amritsar",
  "Kochi",
  "Munnar",
  "Alappuzha",
  "Ooty",
  "Mysuru",
  "Hampi",
  "Puducherry",
  "Darjeeling",
  "Gangtok",
  "Shillong",
  "Jaisalmer",
] as const;